### ISSUE TITLE
Summer of Nix work on OpenXC7

### ISSUE THREAD

**Issue by jleightcap** [openXC7/toolchain-nix#1]
https://github.com/orgs/ngi-nix/teams/moss is picking up Nix packaging (https://github.com/ngi-nix/ngipkgs/issues/7)! We'll be starting to open PRs if this repo if that's alright 🙂

**Comment by hansfbaier** [comment]
That is great! Thanks!

**Comment by hansfbaier** [comment]
I got the devshell to work now, especially the loading of the ghdl plugin into yosys.
It turned out that I had to unset my LD_LIBRARY_PATH variable,
then everything worked as intended.
Many thanks!
