### ISSUE TITLE
Package does not acquire latest prjxray-db

### ISSUE THREAD

**Issue by hansemro** [openXC7/toolchain-nix#11]
This nix package seems to package an older prjxray-db due to openXC7/nextpnr-xilinx submodule pointing to https://github.com/openXC7/prjxray-db/tree/95afd54d7d2ee7c84f542bf3b97e94bb52fcb609. As a workaround, I have been cloning https://github.com/openXC7/prjxray-db and overriding PRJXRAY_DB_DIR inside the nix shell.

**Comment by hansfbaier** [comment]
Thanks for reporting this. Fixed and pushed.
